---
title: "탐데분 최종 결과물"
output:
  pdf_document: default
  html_document: default
date: "2024-05-11"
---

```{r}

#사용한 패키지
library(dplyr)
library(ggplot2)
library(latex2exp)
library(corrplot)
library(forecast)
library(tidyverse)
library(broom)
library(yardstick)
library(lubridate)
library(readr)
library(purrr)
library(showtext)
library(MASS)

# showtext 설정
showtext_auto()

# 사용할 폰트 설정 (예: 나눔고딕)
font_add_google(name = "Nanum Gothic", family = "nanumgothic")
theme_set(theme_gray(base_family = "nanumgothic"))
```

```{r}

#데이터 불러오기
AIR_HOUR_2018 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/AIR_HOUR_2018.csv", encoding = "EUC-KR", fileEncoding = "UTF-8")
AIR_HOUR_2019 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/AIR_HOUR_2019.csv", encoding = "EUC-KR", fileEncoding = "UTF-8")
AIR_HOUR_2020 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/AIR_HOUR_2020.csv", encoding = "EUC-KR", fileEncoding = "UTF-8")
AIR_HOUR_2021 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/AIR_HOUR_2021.csv", encoding = "EUC-KR", fileEncoding = "UTF-8")
AIR_HOUR_2022 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/AIR_HOUR_2022.csv", encoding = "EUC-KR", fileEncoding = "UTF-8")


# "서울특별시 대기오염 측정항목 정보.csv" 파일 읽기
DATA1 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/서울특별시 대기오염 측정항목 정보.csv", encoding = "EUC-KR", fileEncoding = "UTF-8")

# "서울특별시 대기오염 측정소 정보.csv" 파일 읽기
DATA2 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/서울시/서울특별시 대기오염 측정소 정보 .csv", encoding = "EUC-KR", fileEncoding = "UTF-8")


# AIR_HOUR 데이터 프레임들을 리스트로 묶기
AIR_HOUR_list <- list(AIR_HOUR_2018, AIR_HOUR_2019, AIR_HOUR_2020, AIR_HOUR_2021, AIR_HOUR_2022)

# 리스트의 모든 데이터 프레임을 합치기
AIR_HOUR_combined <- do.call(rbind, AIR_HOUR_list)

# 합쳐진 데이터 프레임 정렬하기
AIR_HOUR_ZIP <- arrange(AIR_HOUR_combined, 측정일시)


# 데이터 조인 및 정렬
Seoul <- left_join(left_join(AIR_HOUR_ZIP, DATA2, by = c("측정소.코드" = "측정소.코드")), DATA1, by = c("측정항목" = "측정항목.코드")) %>%
  arrange(측정일시)


# 변수 이름 변경
Seoul1 <- Seoul %>% rename(`측정소 이름` = `측정소.이름`) %>% rename(`측정항목.` = `측정항목.명.줄임.명칭.`)

#실행시간/ 오염 수준 열 생성

Seoul2 <- Seoul1 %>% 
  mutate(`오염 수준` = case_when(
    0 <= 평균값 & 평균값 <= 범례.파랑 ~ "파랑",
    범례.파랑 < 평균값 & 평균값 <= 범례.녹색 ~ "녹색",
    범례.녹색 < 평균값 & 평균값 <= 범례.노랑 ~ "노랑",
    범례.노랑 < 평균값 & 평균값 <= 범례.빨강 ~ "빨강",
    평균값 < 0 ~ as.character(NA),
    범례.빨강 < 평균값 ~ as.character(NA)
  ))


#필요 없는 변수 제거
Seoul3 <- Seoul2 %>% dplyr::select(, -"측정소.코드", -"측정항목", -"국가.기준초과.구분", -"지자체.기준초과.구분", -"측정소.주소", -"표시.순서", -"공인코드", -"통신기호", -"화면.정렬.순서", -"사용여부", -"메인화면.표시", -"소수점.자리.수", -"범례.파랑", -"범례.녹색", -"범례.노랑", -"범례.빨강")



#결측치가 있는 변수 찾기
비율 <- Seoul3 %>% map(is.na) %>% map_dbl(mean)
빈도 <- Seoul3 %>% map(is.na) %>% map_dbl(sum)

tibble(변수명 = names(Seoul3), 비율=비율, 빈도=빈도)

y <- filter(Seoul3, 측정기.상태 == 0 & is.na(`오염 수준`))
yrow <- nrow(y)
yrow
summary(y$평균값)

# 오염 수준 변수 전처리
x <- Seoul3[is.na(Seoul3$`오염 수준`),]

SeoulNA2 <- filter(Seoul3, is.na(`오염 수준`))
#SeoulNA2rows <- nrow(SeoulNA2)
#SeoulNA2rows
unique(SeoulNA2$`측정기.상태`)
table(SeoulNA2$`측정기.상태`)

#측정기 상태 판별하여 0인 것만 남기기
SeoulNA2 %>% filter(`측정기.상태` == 0)

Seoul4 <- filter(Seoul3, !is.na(`오염 수준`))

Seoul4 %>% group_by(`측정기.상태`) %>% summarise(n=n()/nrow(Seoul))
Seoul5 <- Seoul4 %>% filter(`측정기.상태` == 0)


#대기오염 물질별로 최대값이 발생한 날짜, 시각, 지역
Seoul5 %>% group_by(`측정항목.`) %>% filter(which.max(평균값) == row_number())
Seoul5 %>% split(Seoul5$측정항목.) %>% map(function(x) filter(x, x$평균값 == max(x$평균값))) %>% reduce(rbind)

```

```{r}

# 오염물질 그룹 설정
pm_data <- c("PM10", "PM2.5")
gas_data <- c("SO2", "NO2", "O3", "CO")

#가스상 세분화
co_data <- c("CO")
gas_data_1 <- c("SO2", "NO2", "O3")


#반복문으로 그래프 도출
for (target_year_1 in 2018:2022) {
  # 해당 연도의 데이터 추출
  yearly_data_1 <- Seoul5 %>%
    filter(substr(측정일시, 1, 4) == as.character(target_year_1)) %>%
    mutate(연도 = as.character(target_year_1)) 
  
  # 첫 번째 그룹 데이터 추출 및 시각화
  yearly_data_1_pm <- yearly_data_1 %>%
    filter(측정항목. %in% pm_data) %>%
    group_by(측정항목.) %>%
    summarize(평균값 = mean(평균값, na.rm = TRUE))
  
  p1 <- ggplot(yearly_data_1_pm, aes(x=측정항목., y=평균값, fill=측정항목.)) +
    geom_bar(stat="identity") +
    labs(title=paste(target_year_1, "년도 오염물질 평균값 (PM)"), x="측정항목", y="평균값") +
    scale_fill_brewer(palette = "Set3") 
  
  print(p1)
  
  # 두 번째 그룹 데이터 추출 및 시각화
  yearly_data_1_gas <- yearly_data_1 %>%
    filter(측정항목. %in% gas_data) %>%
    group_by(측정항목.) %>%
    summarize(평균값 = mean(평균값, na.rm = TRUE))
  
  p2 <- ggplot(yearly_data_1_gas, aes(x=측정항목., y=평균값, fill=측정항목.)) +
    geom_bar(stat="identity") +
    labs(title=paste(target_year_1, "년도 오염물질 평균값 (Gas)"), x="측정항목", y="평균값") +
    scale_fill_brewer(palette = "Set3") 
  
  print(p2)
  
  # 세 번째 그룹 데이터 추출 및 시각화
  yearly_data_1_gas2 <- yearly_data_1 %>%
    filter(측정항목. %in% gas_data_1) %>%
    group_by(측정항목.) %>%
    summarize(평균값 = mean(평균값, na.rm = TRUE))
  
  p3 <- ggplot(yearly_data_1_gas2, aes(x=측정항목., y=평균값, fill=측정항목.)) +
    geom_bar(stat="identity") +
    labs(title=paste(target_year_1, "년도 오염물질 평균값 (Gas)"), x="측정항목", y="평균값") +
    scale_fill_brewer(palette = "Set3") 
  
  print(p3)
}


# 연도별로 데이터를 그룹화하고 각 오염물질에 대한 평균값을 계산
yearly_avg <- Seoul5 %>%
  mutate(연도 = substr(측정일시, 1, 4)) %>%
  group_by(연도, 측정항목.) %>%
  summarize(평균값 = mean(평균값, na.rm = TRUE))

# pm_data에 대한 그래프 생성
pm_avg <- yearly_avg %>% filter(측정항목. %in% pm_data)
ggplot(pm_avg, aes(x=연도, y=평균값, group=측정항목., color=측정항목.)) +
  geom_line() +
  geom_point() +
  labs(title="연도별 PM 오염물질 변화", x="연도", y="평균값", color="오염물질")


# co_data에 대한 그래프 생성
co_avg <- yearly_avg %>% filter(측정항목. %in% co_data)
ggplot(co_avg, aes(x=연도, y=평균값, group=측정항목., color=측정항목.)) +
  geom_line() +
  geom_point() +
  labs(title="연도별 CO 오염물질 변화", x="연도", y="평균값", color="오염물질")

# gas_data에 대한 그래프 생성
gas_avg_1 <- yearly_avg %>% filter(측정항목. %in% gas_data_1)
ggplot(gas_avg_1, aes(x=연도, y=평균값, group=측정항목., color=측정항목.)) +
  geom_line() +
  geom_point() +
  labs(title="연도별 NO2, O3, SO2 오염물질 변화", x="연도", y="평균값", color="오염물질")

  
#막대그래프로 대기오염 수준을 범주별로 요약
Seoul5plot <- Seoul5
Seoul5plot$`오염 수준` <- factor(Seoul5plot$`오염 수준`, levels = c("파랑", "녹색", "노랑", "빨강"))

Seoul5plot %>% ggplot() +
  geom_bar(width = 0.7, position = "fill", aes(x=`측정항목.`, fill = `오염 수준`)) +
  labs(fill = 'legend', y = '비율',
       title = 'Levels of pollution in Seoul from 2018 to 2022') +
  scale_fill_manual(values = c("#0000FF", "#00FF00", "#FFFF00", "#FF0000"))

```

```{r}
#5년간 미세먼지 평균 배출량 가장 높은 구와 낮은 구 찾기
SeoulBest <- Seoul5 %>% 
  filter(`측정항목.` == "PM10") %>% 
  group_by(`측정소 이름`) %>% 
  summarise(평균값 = mean(`평균값`))

maxcase <- filter(SeoulBest, SeoulBest$평균값 == max(SeoulBest$평균값)) %>% 
  mutate(type = '최댓값')
mincase <- filter(SeoulBest, SeoulBest$평균값 == min(SeoulBest$평균값)) %>% 
  mutate(type = "최솟값")

maxmin <- rbind(maxcase, mincase)
maxmin

#단측 t 검정으로 두 개의 구에서 미세먼지 평균 배출량의 차이 유의 검정
test1 <- Seoul5 %>% filter(`측정소 이름` == "영등포구", `측정항목.`=="PM10") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)
test2<- Seoul5 %>% filter(`측정소 이름` == "성북구", `측정항목.`=="PM10") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)

testdata <- inner_join(test1, test2, by = "측정일시") %>%  mutate(diff = 영등포구-성북구)

t.test(testdata$diff, mu = 0, alternative = "greater", conf.level = 0.95)
```

```{r}
#5년간 초미세먼지 평균 배출량 가장 높은 구와 낮은 구 찾기
SeoulBest <- Seoul5 %>% 
  filter(`측정항목.` == "PM2.5") %>% 
  group_by(`측정소 이름`) %>% 
  summarise(평균값 = mean(`평균값`))

maxcase <- filter(SeoulBest, SeoulBest$평균값 == max(SeoulBest$평균값)) %>% 
  mutate(type = '최댓값')
mincase <- filter(SeoulBest, SeoulBest$평균값 == min(SeoulBest$평균값)) %>% 
  mutate(type = "최솟값")

maxmin <- rbind(maxcase, mincase)
maxmin

#단측 t 검정으로 두 개의 구에서 초미세먼지 평균 배출량의 차이 유의 검정
test1 <- Seoul5 %>% filter(`측정소 이름` == "영등포구", `측정항목.`=="PM2.5") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)
test2<- Seoul5 %>% filter(`측정소 이름` == "성북구", `측정항목.`=="PM2.5") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)

testdata <- inner_join(test1, test2, by = "측정일시") %>%  mutate(diff = 영등포구-성북구)

t.test(testdata$diff, mu = 0, alternative = "greater", conf.level = 0.95)
```

```{r}
# 2019년 이후 데이터 필터링
Seoul5_recent <- Seoul5 %>% filter(substr(측정일시, 1, 4) >= 2019)

# 미세먼지 평균 배출량 계산
SeoulBest_recent <- Seoul5_recent %>% 
  filter(`측정항목.` == "PM10") %>% 
  group_by(`측정소 이름`) %>% 
  summarise(평균값 = mean(`평균값`))

# 평균 배출량이 가장 높은 구와 낮은 구 찾기
maxcase <- filter(SeoulBest_recent, SeoulBest_recent$평균값 == max(SeoulBest_recent$평균값)) %>% 
  mutate(type = '최댓값')
mincase <- filter(SeoulBest_recent, SeoulBest_recent$평균값 == min(SeoulBest_recent$평균값)) %>% 
  mutate(type = "최솟값")

maxmin <- rbind(maxcase, mincase)
maxmin

# 단측 t 검정으로 두 구의 미세먼지 평균 배출량의 차이 유의 검정
# 가장 높은 구와 낮은 구를 변수에 저장
highest_gu <- maxcase$`측정소 이름`
lowest_gu <- mincase$`측정소 이름`

# 데이터 정리
test1 <- Seoul5_recent %>% filter(`측정소 이름` == highest_gu, `측정항목.`=="PM10") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)
test2 <- Seoul5_recent %>% filter(`측정소 이름` == lowest_gu, `측정항목.`=="PM10") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)

testdata <- inner_join(test1, test2, by = "측정일시") %>% mutate(diff = !!sym(highest_gu) - !!sym(lowest_gu))

# 단측 t 검정
t.test(testdata$diff, mu = 0, alternative = "greater", conf.level = 0.95)

```

```{r}
# 2019년 이후 데이터 필터링
Seoul5_recent <- Seoul5 %>% filter(substr(측정일시, 1, 4) >= 2019)

# 초미세먼지 평균 배출량 계산
SeoulBest_recent <- Seoul5_recent %>% 
  filter(`측정항목.` == "PM2.5") %>% 
  group_by(`측정소 이름`) %>% 
  summarise(평균값 = mean(`평균값`))

# 평균 배출량이 가장 높은 구와 낮은 구 찾기
maxcase <- filter(SeoulBest_recent, SeoulBest_recent$평균값 == max(SeoulBest_recent$평균값)) %>% 
  mutate(type = '최댓값')
mincase <- filter(SeoulBest_recent, SeoulBest_recent$평균값 == min(SeoulBest_recent$평균값)) %>% 
  mutate(type = "최솟값")

maxmin <- rbind(maxcase, mincase)
maxmin

# 단측 t 검정으로 두 구의 초미세먼지 평균 배출량의 차이 유의 검정
# 가장 높은 구와 낮은 구를 변수에 저장
highest_gu <- maxcase$`측정소 이름`
lowest_gu <- mincase$`측정소 이름`

# 데이터 정리
test1 <- Seoul5_recent %>% filter(`측정소 이름` == highest_gu, `측정항목.`=="PM2.5") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)
test2 <- Seoul5_recent %>% filter(`측정소 이름` == lowest_gu, `측정항목.`=="PM2.5") %>% 
  dplyr::select(측정일시, `측정소 이름`, 평균값) %>% spread(key = `측정소 이름`, value =평균값)

testdata <- inner_join(test1, test2, by = "측정일시") %>% mutate(diff = !!sym(highest_gu) - !!sym(lowest_gu))

# 단측 t 검정
t.test(testdata$diff, mu = 0, alternative = "greater", conf.level = 0.95)

```

```{r}

```

```{r}
# 측정일시 열을 날짜/시간 형식으로 변환하기 위해 필요한 문자열 연산을 수행
Seoul6 <- Seoul5 %>%
  mutate(측정일시 = as.POSIXct(paste0(substr(측정일시, 1, 8), " ", substr(측정일시, 9, 10), ":00:00"), format = "%Y%m%d %H:%M:%S"))

Seoul7 <- Seoul6 %>% mutate(
  `년도`= year(`측정일시`),
  `월` = sprintf("%02d", month(`측정일시`)),
  `일` = mday(`측정일시`),
  `시` = hour(`측정일시`)
)


#월별로 미세먼지 평균값 변화의 경향 파악하기 
subtitle <- sprintf("Date : %s/%s ~ %s/%s", year(Seoul7[[1,1]]), month(Seoul7[[1,1]]), year(Seoul7[[nrow(Seoul7),1]]), month(Seoul7[[nrow(Seoul7),1]]))

subtitle

y_name <- "평균값($\\mu g/m^3$)"
y_name
```

```{r}
# PM10과 PM2.5에 대한 데이터만 추출
Seoul7_pm <- Seoul7 %>%
  filter(측정항목. %in% c("PM10", "PM2.5"))

# 연도별 월별 평균값 계산
Seoul7_monthly <- Seoul7_pm %>%
  mutate(년도 = as.integer(년도),
         월 = as.integer(월),
         일 = as.integer(일)) %>%
  group_by(년도, 월, 측정항목.) %>%
  summarize(평균값 = mean(평균값))

# 연도별 월별 미세먼지 변화 시각화
ggplot(Seoul7_monthly, aes(x = `월`, y = `평균값`, color = `측정항목.`)) +
  geom_line() +
  scale_x_continuous(breaks = 1:12) +
  facet_wrap(~년도, nrow = 1) +
  labs(title = "연도별 월별 PM10과 PM2.5 미세먼지 변화",
       x = "월",
       y = latex2exp::TeX(y_name),
       color = "측정항목")

#미세먼지 경향 파악
Seoul7 %>%  group_by(`월`, `측정항목.`) %>% 
  summarise(`평균값` = mean(`평균값`)) %>% 
  filter(`측정항목.` %in% c("PM10", "PM2.5")) %>% 
  ggplot() + geom_line(aes(x = `월`, y = `평균값`, group = `측정항목.`, color = `측정항목.`)) +
  labs(x = "월", y = latex2exp::TeX(y_name), 
       title = "PM10, PM2.5 value for each month", subtitle = subtitle)
```

```{r}
#계절성 파악하기

# 필요한 데이터 추출 및 정리
Seoul7$측정일시 <- as.POSIXct(Seoul7$측정일시, format="%Y-%m-%d %H:%M:%S")
Seoul7_PM10 <- Seoul7 %>% filter(측정항목. == "PM10")
Seoul7_PM25 <- Seoul7 %>% filter(측정항목. == "PM2.5")

# 월별 평균값 계산
monthly_PM10 <- Seoul7_PM10 %>% 
  mutate(Month = format(측정일시, "%Y-%m")) %>%
  group_by(Month) %>%
  summarise(PM10 = mean(평균값))

monthly_PM25 <- Seoul7_PM25 %>% 
  mutate(Month = format(측정일시, "%Y-%m")) %>%
  group_by(Month) %>%
  summarise(PM25 = mean(평균값))

# 시계열 데이터 생성
ts_PM10 <- ts(monthly_PM10$PM10, frequency=12, start=c(as.numeric(substr(monthly_PM10$Month[1], 1, 4)), as.numeric(substr(monthly_PM10$Month[1], 6, 7))))
ts_PM25 <- ts(monthly_PM25$PM25, frequency=12, start=c(as.numeric(substr(monthly_PM25$Month[1], 1, 4)), as.numeric(substr(monthly_PM25$Month[1], 6, 7))))

# 계절성 분해
decompose_PM10 <- stl(ts_PM10, s.window="periodic")
decompose_PM25 <- stl(ts_PM25, s.window="periodic")

# 계절성 부분만 시각화
plot(decompose_PM10$time.series[, "seasonal"], main="Seasonal Component of PM10", ylab="Seasonal", xlab="Time")
plot(decompose_PM25$time.series[, "seasonal"], main="Seasonal Component of PM2.5", ylab="Seasonal", xlab="Time")
```

```{r}
#대기오염 물질 사이의 관계 찾기 위한 데이터셋의 변수 정리
Seoul8 <- Seoul7 %>% dplyr::select(측정일시, `측정소 이름`,`측정항목.`, 평균값)

Seoul9 <- spread(Seoul8, 측정항목., 평균값) %>% dplyr::select(-측정일시, -`측정소 이름`) %>% dplyr::select(CO, NO2, SO2, O3, PM10, PM2.5)

#전처리
Seoul10 <- Seoul9 %>% drop_na()

#상관관계 행렬도
cor_Seoul <- cor(Seoul10)
cor_Seoul

#상관관계 plot
corrplot(cor_Seoul, type="lower", method="number")

# 정규성 검정을 위한 샤피로-위프 테스트 수행
#shapiro_test_result <- shapiro.test(Seoul10$평균값)

# 결과 출력
#shapiro_test_result

# 스피어만 상관관계 행렬 계산
#cor_Seoul_spearman <- cor(Seoul10, method = "spearman")
#cor_Seoul_spearman

# 상관관계 plot
#corrplot(cor_Seoul_spearman, type = "lower", method = "number")
```

```{r}
#NO2와 O3관계 알아보기
Seoul7 %>% group_by(`월`, `측정항목.`) %>% 
  summarise(`평균값` = mean(`평균값`)) %>%
  filter(`측정항목.` %in% c("NO2", "O3")) %>%
  ggplot()+ geom_line(aes(x=`월`, y=`평균값`, group = 측정항목., color=`측정항목.`))

Seoul7 %>% group_by(`시`, `측정항목.`) %>% 
  summarise(`평균값` = mean(`평균값`)) %>%
  filter(`측정항목.` %in% c("NO2", "O3")) %>%
  ggplot()+ geom_line(aes(x=`시`, y=`평균값`, group = 측정항목., color=`측정항목.`))
```

```{r}
#모형을 통한 대기오염 물질의 계절에 따른 변화

#5년간 이산화질소(NO2) 평균 농도가 가장 큰 구의 NO2 평균값 시각화
badAirGoo <- Seoul5 %>% filter(`측정항목.`== "NO2") %>% 
  group_by(`측정소 이름`) %>% 
  summarise(`이산화질소 평균 농도` = mean(평균값)) %>% 
  arrange(desc(`이산화질소 평균 농도`)) %>% .[[1,1]]

#NO2 평균 농도 높은 지역 찾기
Seoul11 <- Seoul6 %>% filter(
  `측정소 이름` == badAirGoo, `측정항목.`=="NO2"
)

Seoul12 <- Seoul11 %>% arrange(측정일시) %>% 
  mutate(월 = month(측정일시), 연도 = year(측정일시))

mday(Seoul12$측정일시) <- 1
Seoul12$측정일시 <- as_date(Seoul12$측정일시)

#해당 지역 평균 농도 나타내기
Seoul12 <- Seoul12 %>%group_by(측정일시) %>% summarise(NO2 = mean(`평균값`))

ggplot(Seoul12, aes(측정일시, `NO2`)) +
  geom_point(color = 'red', size = 2) +
  geom_line()
```

```{r}
#톨게이트 데이터 하나로 합치기

# 파일 경로 설정
file_path <- "/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/톨게이트 데이터"

# 디렉토리에서 모든 CSV 파일을 읽어서 단일 데이터 프레임으로 결합
all_data <- list.files(path = file_path, pattern = "\\.csv$", full.names = TRUE) %>%
  map_df(~read_csv(.x, locale = locale(encoding = "UTF-8")))

# "날짜" 열을 날짜 형식으로 변환 후 정렬
sorted_data <- all_data %>%
  mutate(날짜 = ymd(날짜)) %>%
  arrange(날짜)

#"합계" 행만 남기기

# "입구"와 "출구"에 해당하는 행을 제외
filtered_data <- sorted_data %>%
  filter(자료종류 != "입구", 자료종류 != "출구")

# 출퇴근 시간 열들만 남기기

#원하지 않는 시간대 열 이름을 지정
columns_to_remove <- c("00시", "01시", "02시", "03시", "04시", "10시", 
                       "11시", "12시", "13시", "14시", "15시", "16시", 
                       "17시", "23시")

# 해당 열을 제외하고 나머지 데이터를 선택
filtered_data <- filtered_data %>%
  dplyr::select(-one_of(columns_to_remove))

#톨게이트 시간대별로 합치기
result_filtered_data <- filtered_data %>%
  group_by(날짜) %>%
  summarise(
    `05시` = sum(`05시`, na.rm = TRUE),
    `06시` = sum(`06시`, na.rm = TRUE),
    `07시` = sum(`07시`, na.rm = TRUE),
    `08시` = sum(`08시`, na.rm = TRUE),
    `09시` = sum(`09시`, na.rm = TRUE),
    `18시` = sum(`18시`, na.rm = TRUE),
    `19시` = sum(`19시`, na.rm = TRUE),
    `20시` = sum(`20시`, na.rm = TRUE),
    `21시` = sum(`21시`, na.rm = TRUE),
    `22시` = sum(`22시`, na.rm = TRUE)
  )

# result_filtered_data의 날짜를 Date 형식으로 변환 (이미 YYYY-MM-DD 형식이라면 변환 필요 없음)
result_filtered_data$날짜 <- as.Date(result_filtered_data$날짜, format="%Y-%m-%d")

# 톨게이트 별로 필터링
filtered_data_gunja <- filter(filtered_data, 영업소 == "군자")
filtered_data_WSeoul <- filter(filtered_data, 영업소 == "서서울")
filtered_data_Seoul <- filter(filtered_data, 영업소 == "서울")

# 아침 시간대 (05시~09시) 및 저녁 시간대 (18시~22시) 데이터 선택
morning_times <- c("05시", "06시", "07시", "08시", "09시")
evening_times <- c("18시", "19시", "20시", "21시", "22시")

#출근 시간 데이터 분류
morning_traffic_gunja <- dplyr::select(filtered_data_gunja , all_of(morning_times))
morning_traffic_WSeoul <- dplyr::select(filtered_data_WSeoul, all_of(morning_times))
morning_traffic_Seoul <- dplyr::select(filtered_data_Seoul, all_of(morning_times))

#데이터 프레임 그룹화 해제
morning_traffic_gunja <- ungroup(morning_traffic_gunja)
morning_traffic_WSeoul <- ungroup(morning_traffic_WSeoul)
morning_traffic_Seoul <- ungroup(morning_traffic_Seoul)

#데이터 벡터로 변환
morning_traffic_gunja_vector <- unlist(morning_traffic_gunja, use.names = FALSE)
morning_traffic_WSeoul_vector <- unlist(morning_traffic_WSeoul, use.names = FALSE)
morning_traffic_Seoul_vector <- unlist(morning_traffic_Seoul, use.names = FALSE)

#퇴근 시간 데이터 분류
evening_traffic_gunja <- dplyr::select(filtered_data_gunja , all_of(evening_times))
evening_traffic_WSeoul <- dplyr::select(filtered_data_WSeoul, all_of(evening_times))
evening_traffic_Seoul<- dplyr::select(filtered_data_Seoul, all_of(evening_times))

#데이터 프레임 그룹화 해제
evening_traffic_gunja <- ungroup(evening_traffic_gunja)
evening_traffic_WSeoul <- ungroup(evening_traffic_WSeoul)
evening_traffic_Seoul <- ungroup(evening_traffic_Seoul)

#데이터 벡터로 변환
evening_traffic_gunja_vector <- unlist(morning_traffic_gunja, use.names = FALSE)
evening_traffic_WSeoul_vector <- unlist(morning_traffic_WSeoul, use.names = FALSE)
evening_traffic_Seoul_vector <- unlist(morning_traffic_Seoul, use.names = FALSE)

```

```{r}
# NO2에 대한 데이터만 추출
Seoul7_NO2 <- Seoul7 %>%
  filter(측정항목. %in% c("NO2"))

# NO2와 교통량 상관관계 
# 데이터 셋 불러오기
confuse_data_NO2 <- Seoul7_NO2

# "시" 열의 값이 5, 6, 7, 8, 9, 18, 19, 20, 21, 22 인 행만 남기기
confuse_data_NO2 <- confuse_data_NO2 %>%
  filter(시 %in% c(5, 6, 7, 8, 9, 18, 19, 20, 21, 22))

# '측정항목'이 'NO2'인 행만 추출
NO2_data <- filter(confuse_data_NO2, 측정항목. == 'NO2')

# '년', '월', '시' 변수를 기준으로 그룹화하여 평균값 계산
daily_NO2_mean <- NO2_data %>%
  group_by(년도, 월, 일, 시) %>%
  summarise(평균값 = mean(평균값))

# '시' 변수의 값을 새로운 변수로 지정하고, 해당 시간에 대한 평균값을 새로운 변수의 값으로 배정
daily_NO2_mean <- daily_NO2_mean %>%
  mutate(시 = case_when(
    시 == 5 ~ "05시",
    시 == 6 ~ "06시",
    시 == 7 ~ "07시",
    시 == 8 ~ "08시",
    시 == 9 ~ "09시",
    시 == 18 ~ "18시",
    시 == 19 ~ "19시",
    시 == 20 ~ "20시",
    시 == 21 ~ "21시",
    시 == 22 ~ "22시",
    TRUE ~ NA_character_
  ))

# 데이터를 wide format으로 변환
wide_NO2_data <- daily_NO2_mean %>%
  dplyr::select(시, 평균값) %>%
  pivot_wider(names_from = 시, values_from = 평균값)

#행 두개 차이 나는거 찾아서 지우기

# wide_NO2_datas의 년도, 월, 일을 결합하여 YYYY-MM-DD 형식으로 변환
wide_NO2_data <- wide_NO2_data %>%
  unite("날짜", c(년도, 월, 일), sep="-", remove=FALSE) %>%
  mutate(날짜 = ymd(날짜))

# wide_NO2_datas에만 있는 날짜 찾기
only_in_wide_NO2 <- anti_join(wide_NO2_data, result_filtered_data, by="날짜")

# wide_NO2_datas에서 해당 행 제거
wide_NO2_data_filtered <- filter(wide_NO2_data, !날짜 %in% only_in_wide_NO2$날짜)

# 결과 확인
print(nrow(wide_NO2_data))
print(nrow(wide_NO2_data_filtered))

# 데이터 프레임 그룹화 해제
wide_NO2_data_filtered_ungrouped <- ungroup(wide_NO2_data_filtered)

# 그룹화 해제된 데이터 프레임에서 '년도', '월', '일' 열 제거
morning_NO2 <- dplyr::select(wide_NO2_data_filtered_ungrouped, -`년도`, -`월`, -`일`)

# 아침 시간대의 데이터 합치기
morning_NO2 <- dplyr::select(morning_NO2, all_of(morning_times))

# 데이터를 벡터 형태로 변환
morning_NO2_vector <- unlist(morning_NO2, use.names = FALSE)

#퇴근

# 그룹화 해제된 데이터 프레임에서 '년도', '월', '일' 열 제거
evening_NO2 <- dplyr::select(wide_NO2_data_filtered_ungrouped, -`년도`, -`월`, -`일`)

# 저녁 시간대의 데이터 합치기
evening_NO2 <- dplyr::select(wide_NO2_data_filtered_ungrouped, all_of(evening_times))

# 데이터 프레임 그룹화 해제
evening_NO2 <- ungroup(evening_NO2 )

# 데이터를 벡터 형태로 변환
evening_NO2_vector <- unlist(evening_NO2, use.names = FALSE)

# 아침 시간대의 상관관계 계산
morning_correlation_gunja <- cor(morning_NO2_vector, morning_traffic_gunja_vector, use="complete.obs")
morning_correlation_WSeoul <- cor(morning_NO2_vector, morning_traffic_WSeoul_vector, use="complete.obs")
morning_correlation_Seoul <- cor(morning_NO2_vector, morning_traffic_Seoul_vector, use="complete.obs")

# 저녁 시간대의 상관관계 계산
evening_correlation_gunja <- cor(evening_NO2_vector, evening_traffic_gunja_vector, use="complete.obs")
evening_correlation_WSeoul <- cor(evening_NO2_vector, evening_traffic_WSeoul_vector, use="complete.obs")
evening_correlation_Seoul <- cor(evening_NO2_vector, evening_traffic_Seoul_vector, use="complete.obs")

# 결과 출력
cat("출근 시간대의 교통량과 질소산화물 농도의 상관관계(군자):", morning_correlation_gunja, "\n")
cat("출근 시간대의 교통량과 질소산화물 농도의 상관관계(서서울):", morning_correlation_WSeoul, "\n")
cat("출근 시간대의 교통량과 질소산화물 농도의 상관관계(서울):", morning_correlation_Seoul, "\n")
cat("퇴근 시간대의 교통량과 질소산화물 농도의 상관관계(군자):", evening_correlation_gunja, "\n")
cat("퇴근 시간대의 교통량과 질소산화물 농도의 상관관계(서서울):", evening_correlation_WSeoul, "\n")
cat("퇴근 시간대의 교통량과 질소산화물 농도의 상관관계(서울):", evening_correlation_Seoul)

```

```{r}
#미세먼지 상관관계 
# 데이터 셋 불러오기
confuse_data <- Seoul7_pm

# "시" 열의 값이 5, 6, 7, 8, 9, 18, 19, 20, 21, 22 인 행만 남기기
confused_data <- confuse_data %>%
  filter(시 %in% c(5, 6, 7, 8, 9, 18, 19, 20, 21, 22))

# '측정항목'이 'PM10'인 행만 추출
pm10_data <- filter(confused_data, 측정항목. == 'PM10')

# '년', '월', '시' 변수를 기준으로 그룹화하여 평균값 계산
daily_pm10_mean <- pm10_data %>%
  group_by(년도, 월, 일, 시) %>%
  summarise(평균값 = mean(평균값))

# '시' 변수의 값을 새로운 변수로 지정하고, 해당 시간에 대한 평균값을 새로운 변수의 값으로 배정
daily_pm10_mean <- daily_pm10_mean %>%
  mutate(시 = case_when(
    시 == 5 ~ "05시",
    시 == 6 ~ "06시",
    시 == 7 ~ "07시",
    시 == 8 ~ "08시",
    시 == 9 ~ "09시",
    시 == 18 ~ "18시",
    시 == 19 ~ "19시",
    시 == 20 ~ "20시",
    시 == 21 ~ "21시",
    시 == 22 ~ "22시",
    TRUE ~ NA_character_
))

# 데이터를 wide format으로 변환
wide_pm10_data <- daily_pm10_mean %>%
  dplyr::select(시, 평균값) %>%
  pivot_wider(names_from = 시, values_from = 평균값)

#행 두개 차이 나는거 찾아서 지우기

# wide_pm10_datas의 년도, 월, 일을 결합하여 YYYY-MM-DD 형식으로 변환
wide_pm10_data <- wide_pm10_data %>%
  unite("날짜", c(년도, 월, 일), sep="-", remove=FALSE) %>%
  mutate(날짜 = ymd(날짜))


# wide_pm10_datas에만 있는 날짜 찾기
only_in_wide <- anti_join(wide_pm10_data, result_filtered_data, by="날짜")

# wide_pm10_datas에서 해당 행 제거
wide_pm10_data_filtered <- filter(wide_pm10_data, !날짜 %in% only_in_wide$날짜)

# 결과 확인
print(nrow(wide_pm10_data))
print(nrow(wide_pm10_data_filtered))

# 데이터 프레임 그룹화 해제
wide_pm10_data_filtered_ungrouped <- ungroup(wide_pm10_data_filtered)

# 그룹화 해제된 데이터 프레임에서 '년도', '월', '일' 열 제거
morning_pm10 <- dplyr::select(wide_pm10_data_filtered_ungrouped, -`년도`, -`월`, -`일`)

# 아침 시간대의 데이터 합치기
morning_pm10 <- dplyr::select(morning_pm10, all_of(morning_times))

#시간만 남기기
#morning_traffic_gunja <- select(morning_traffic_gunja, -`날짜`)
#morning_traffic_WSeoul <- select(morning_traffic_WSeoul, -`날짜`)
#morning_traffic_Seoul <- select(morning_traffic_Seoul, -`날짜`)

# 데이터를 벡터 형태로 변환
morning_pm10_vector <- unlist(morning_pm10, use.names = FALSE)

#퇴근

# 그룹화 해제된 데이터 프레임에서 '년도', '월', '일' 열 제거
evening_pm10 <- dplyr::select(wide_pm10_data_filtered_ungrouped, -`년도`, -`월`, -`일`)

# 저녁 시간대의 데이터 합치기
evening_pm10 <- dplyr::select(wide_pm10_data_filtered_ungrouped, all_of(evening_times))

# 데이터 프레임 그룹화 해제
evening_pm10  <- ungroup(evening_pm10 )

#시간만 남기기
#evening_pm10 <- select(evening_pm10) #, -`년도`, -`월`, -`일`)
#evening_traffic_gunja <- select(evening_traffic_gunja) #, -`날짜`)
#evening_traffic_WSeoul <- select(evening_traffic_WSeoul) #, -`날짜`)
#evening_traffic_Seoul <- select(evening_traffic_Seoul) #, -`날짜`)

# 데이터를 벡터 형태로 변환
evening_pm10_vector <- unlist(evening_pm10, use.names = FALSE)

#evening_pm10_vector

#class(evening_pm10_vector)
#class(evening_traffic_vector)

# 데이터 유형을 수치형으로 변환
#morning_pm10_vector <- as.numeric(morning_pm10_vector)
#morning_traffic_vector <- as.numeric(morning_traffic_vector)

# NA 값 제거
#morning_pm10_vector <- na.omit(morning_pm10_vector)
#morning_traffic_vector <- na.omit(morning_traffic_vector)

# 출근 시간대의 상관관계 계산
morning_correlation_gunja <- cor(morning_pm10_vector, morning_traffic_gunja_vector, use="complete.obs")
morning_correlation_WSeoul <- cor(morning_pm10_vector, morning_traffic_WSeoul_vector, use="complete.obs")
morning_correlation_Seoul <- cor(morning_pm10_vector, morning_traffic_Seoul_vector, use="complete.obs")

# 퇴근 시간대의 상관관계 계산
evening_correlation_gunja <- cor(evening_pm10_vector, evening_traffic_gunja_vector, use="complete.obs")
evening_correlation_WSeoul <- cor(evening_pm10_vector, evening_traffic_WSeoul_vector, use="complete.obs")
evening_correlation_Seoul <- cor(evening_pm10_vector, evening_traffic_Seoul_vector, use="complete.obs")

# 결과 출력
cat("출근 시간대의 교통량과 미세먼지 농도의 상관관계(군자):", morning_correlation_gunja, "\n")
cat("출근 시간대의 교통량과 미세먼지 농도의 상관관계(서서울):", morning_correlation_WSeoul, "\n")
cat("출근 시간대의 교통량과 미세먼지 농도의 상관관계(서울):", morning_correlation_Seoul, "\n")
cat("퇴근 시간대의 교통량과 미세먼지 농도의 상관관계(군자):", evening_correlation_gunja, "\n")
cat("퇴근 시간대의 교통량과 미세먼지 농도의 상관관계(서서울):", evening_correlation_WSeoul, "\n")
cat("퇴근 시간대의 교통량과 미세먼지 농도의 상관관계(서울):", evening_correlation_Seoul)

```

```{r}
#초미세먼지 상관관계 

# 데이터 셋 불러오기
confuse_data_1 <- Seoul7_pm

# "시" 열의 값이 5, 6, 7, 8, 9, 18, 19, 20, 21, 22 인 행만 남기기
confused_data_1 <- confuse_data_1 %>%
  filter(시 %in% c(5, 6, 7, 8, 9, 18, 19, 20, 21, 22))

# '측정항목'이 'PM2.5'인 행만 추출
pm2.5_data <- filter(confused_data_1, 측정항목. == 'PM2.5')

# '년', '월', '시' 변수를 기준으로 그룹화하여 평균값 계산
daily_pm2.5_mean <- pm2.5_data %>%
  group_by(년도, 월, 일, 시) %>%
  summarise(평균값 = mean(평균값))

# '시' 변수의 값을 새로운 변수로 지정하고, 해당 시간에 대한 평균값을 새로운 변수의 값으로 배정
daily_pm2.5_mean <- daily_pm2.5_mean %>%
  mutate(시 = case_when(
    시 == 5 ~ "05시",
    시 == 6 ~ "06시",
    시 == 7 ~ "07시",
    시 == 8 ~ "08시",
    시 == 9 ~ "09시",
    시 == 18 ~ "18시",
    시 == 19 ~ "19시",
    시 == 20 ~ "20시",
    시 == 21 ~ "21시",
    시 == 22 ~ "22시",
    TRUE ~ NA_character_
  ))

# 데이터를 wide format으로 변환
wide_pm2.5_data <- daily_pm2.5_mean %>%
  dplyr::select(시, 평균값) %>%
  pivot_wider(names_from = 시, values_from = 평균값)


# wide_pm2.5_datas의 년도, 월, 일을 결합하여 YYYY-MM-DD 형식으로 변환
wide_pm2.5_data <- wide_pm2.5_data %>%
  unite("날짜", c(년도, 월, 일), sep="-", remove=FALSE) %>%
  mutate(날짜 = ymd(날짜))

# result_filtered_data의 날짜를 Date 형식으로 변환 (이미 YYYY-MM-DD 형식이라면 변환 필요 없음)
result_filtered_data$날짜 <- as.Date(result_filtered_data$날짜, format="%Y-%m-%d")

# wide_pm2.5_datas에만 있는 날짜 찾기
only_in_wide_1 <- anti_join(wide_pm2.5_data, result_filtered_data, by="날짜")

# wide_pm2.5_datas에서 해당 행 제거
wide_pm2.5_data_filtered <- filter(wide_pm2.5_data, !날짜 %in% only_in_wide_1$날짜)


```

```{r}
#각 시간별로 상관관계 계산

# 아침 시간대 (05시~09시) 및 저녁 시간대 (18시~22시) 데이터 선택
morning_times <- c("05시", "06시", "07시", "08시", "09시")
evening_times <- c("18시", "19시", "20시", "21시", "22시")

# 데이터 프레임 그룹화 해제
wide_pm2.5_data_filtered_ungrouped <- ungroup(wide_pm2.5_data_filtered)

# 그룹화 해제된 데이터 프레임에서 '년도', '월', '일' 열 제거
morning_pm2.5 <- dplyr::select(wide_pm2.5_data_filtered_ungrouped, -`년도`, -`월`, -`일`)

# 아침 시간대의 데이터 합치기
morning_pm2.5 <- dplyr::select(morning_pm2.5, all_of(morning_times))

# 데이터를 벡터 형태로 변환
morning_pm2.5_vector <- unlist(morning_pm2.5, use.names = FALSE)


# 그룹화 해제된 데이터 프레임에서 '년도', '월', '일' 열 제거
evening_pm2.5 <- dplyr::select(wide_pm2.5_data_filtered_ungrouped, -`년도`, -`월`, -`일`)

# 저녁 시간대의 데이터 합치기
evening_pm2.5 <- dplyr::select(wide_pm2.5_data_filtered, all_of(evening_times))

# 데이터 프레임 그룹화 해제
evening_pm2.5  <- ungroup(evening_pm2.5)

#시간만 남기기
evening_pm2.5 <- dplyr::select(evening_pm2.5, -`년도`, -`월`, -`일`)

# 데이터를 벡터 형태로 변환
evening_pm2.5_vector <- unlist(evening_pm2.5, use.names = FALSE)
```

```{r}
# 아침 시간대의 상관관계 계산
morning_correlation_gunja <- cor(morning_pm2.5_vector, morning_traffic_gunja_vector, use="complete.obs")
morning_correlation_WSeoul <- cor(morning_pm2.5_vector, morning_traffic_WSeoul_vector, use="complete.obs")
morning_correlation_Seoul <- cor(morning_pm2.5_vector, morning_traffic_Seoul_vector, use="complete.obs")

# 저녁 시간대의 상관관계 계산
evening_correlation_gunja <- cor(evening_pm2.5_vector, evening_traffic_gunja_vector, use="complete.obs")
evening_correlation_WSeoul <- cor(evening_pm2.5_vector, evening_traffic_WSeoul_vector, use="complete.obs")
evening_correlation_Seoul <- cor(evening_pm2.5_vector, evening_traffic_Seoul_vector, use="complete.obs")

# 결과 출력
cat("출근 시간대의 교통량과 미세먼지 농도의 상관관계(군자):", morning_correlation_gunja, "\n")
cat("출근 시간대의 교통량과 미세먼지 농도의 상관관계(서서울):", morning_correlation_WSeoul, "\n")
cat("출근 시간대의 교통량과 미세먼지 농도의 상관관계(서울):", morning_correlation_Seoul, "\n")
cat("퇴근 시간대의 교통량과 미세먼지 농도의 상관관계(군자):", evening_correlation_gunja, "\n")
cat("퇴근 시간대의 교통량과 미세먼지 농도의 상관관계(서서울):", evening_correlation_WSeoul, "\n")
cat("퇴근 시간대의 교통량과 미세먼지 농도의 상관관계(서울):", evening_correlation_Seoul)
```
```{r}
#기상청 데이터 불러오기

weather_2018 <- read.csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/기상청/기상청 2018.csv", encoding = "UTF-8")
weather_2019 <- read_csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/기상청/기상청 2019.csv", locale = locale(encoding = "UTF-8"))
weather_2020 <- read_csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/기상청/기상청 2020.csv", locale = locale(encoding = "UTF-8"))
weather_2021 <- read_csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/기상청/기상청 2021.csv", locale = locale(encoding = "UTF-8"))
weather_2022 <- read_csv("/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/기상청/기상청 2022.csv", locale = locale(encoding = "UTF-8"))


#기싱청 데이터 합치기
weatherList <- list(weather_2018, weather_2019, weather_2020, weather_2021, weather_2022)

# 각 데이터 프레임의 열 이름 확인
lapply(weatherList, names)

# 모든 데이터 프레임의 열 이름이 같은지 확인
#all_equal(names(weatherList))

# 열 이름이 일치하지 않는 경우 각 데이터 프레임의 열 이름을 통일
names(weatherList[[2]]) <- names(weatherList[[1]])
names(weatherList[[3]]) <- names(weatherList[[1]])
names(weatherList[[4]]) <- names(weatherList[[1]])
names(weatherList[[5]]) <- names(weatherList[[1]])

#데이터 프레임 정렬
weather_combined <- do.call(rbind, weatherList)
weather_zip <- arrange(weather_combined, 일시)

#일시 형식 바꾸기 

# 일시 열을 분할하여 날짜와 시간 열 생성
weather_zip <- weather_zip %>%
  separate(일시, into = c("날짜", "시간"), sep = " ") %>%
  mutate(시간 = gsub(":.*", "", 시간))  # 시간에서 분 이후를 제거하여 숫자로 변환하기 위함

# 시간 열을 숫자형으로 변환하여 정렬
weather_zip <- weather_zip %>%
  mutate(시간 = as.numeric(시간)) %>%
  arrange(날짜, 시간)

# 필요에 따라 날짜와 시간을 다시 결합
weather_zip <- weather_zip %>%
  mutate(일시 = paste(날짜, 시간, sep = " ")) %>%
  dplyr::select(-c(날짜, 시간))  # 필요한 경우 날짜와 시간 열을 제거

```

```{r}

# 1. '지점' 열 삭제
weather_zip <- dplyr::select(weather_zip, -지점)

# 2. '지점명' 변수 값 중 "강북*"을 "강북"으로 바꿈
weather_zip$지점명 <- gsub("강북.*", "강북", weather_zip$지점명)

# 3. '지점명' 변수 값 중 "북악산"을 "종로구"로 바꿈
weather_zip$지점명 <- gsub("북악산", "종로구", weather_zip$지점명)

# 4. '지점명' 값이 "기상청"이면 "동작구"로 바꿈
weather_zip$지점명 <- gsub("기상청", "동작구", weather_zip$지점명)

# 5. '현충원'이 포함된 행 삭제
weather_zip <- filter(weather_zip, 지점명 != "현충원")

#6. '지점명' 열의 값에 '구' 붙이기 (단, '종로구'는 제외)
weather_zip$지점명 <- ifelse(weather_zip$지점명 != "종로구" & !grepl("구$", weather_zip$지점명), paste0(weather_zip$지점명, "구"), weather_zip$지점명)

#7. 두 데이터프레임 비교: weather_zip의 지점명 중 Seoul7의 측정소 이름에 없는 값 찾기
unique_values <- anti_join(weather_zip, Seoul7, by = c("지점명" = "측정소 이름"))

#8. '한강구', '남현구' 열 삭제
weather_zip <- filter(weather_zip, 지점명 != "한강구")
weather_zip <- filter(weather_zip, 지점명 != "남현구")

#9. Part2에서 썼던 데이터 불러와서 spread
SeoulPt2 <- Seoul7 %>% 
  dplyr::select(`측정일시`, `측정소 이름`, `평균값`, `측정항목.`) %>% 
  spread(key=`측정항목.`, value=`평균값`)

#결측치 있는 행 제거
SeoulPt2<- na.omit(SeoulPt2)

#측정일시 형식 변경
SeoulPt2$측정일시 <- strptime(SeoulPt2$측정일시, format="%Y-%m-%d %H:%M:%S")
SeoulPt2$측정일시 <- format(SeoulPt2$측정일시, "%Y-%m-%d %H")

SeoulPt2$측정일시[1:24] <- ifelse(is.na(SeoulPt2$측정일시[1:24]), "2018-01-01 00", SeoulPt2$측정일시[1:24])

weather_zip$일시 <- strptime(weather_zip$일시, format="%Y.%m.%d %H")
weather_zip$일시 <- format(weather_zip$일시, "%Y-%m-%d %H")

#데이터 파일 합치기
SeoulWeather <- inner_join(SeoulPt2, weather_zip, by = c("측정일시" = "일시", "측정소 이름" = "지점명"))

```

```{r}
SeoulWeather1 <- read.csv('/Users/hoamiw/Desktop/통계 대회/응정통/사용 데이터/SeoulWeather.csv') # 데

# 풍향을 방위로 변환하는 함수 정의
wind_direction <- function(deg) {
  if (is.na(deg)) {
    return(NA)
  } else if (deg == 0) {
    return("N")
  } else if (deg > 0 && deg <= 45) {
    return("NE")
  } else if (deg > 45 && deg <= 90) {
    return("E")
  } else if (deg > 90 && deg <= 135) {
    return("SE")
  } else if (deg > 135 && deg <= 180) {
    return("S")
  } else if (deg > 180 && deg <= 225) {
    return("SW")
  } else if (deg > 225 && deg <= 270) {
    return("W")
  } else if (deg > 270 && deg <= 315) {
    return("NW")
  } else if (deg > 315 && deg <= 360) {
    return("N")
  } else {
    return(NA)
  }
}

# 풍향을 방위로 변환
SeoulWeather1$풍향방위 <- sapply(SeoulWeather1$풍향.deg., wind_direction)

# NA 값을 제외한 계절별 및 풍향별 데이터 그룹화 및 총합 계산
seasonal_wind_data <- SeoulWeather1 %>%
  filter(!is.na(풍향방위)) %>%
  group_by(Season, 풍향방위) %>%
  summarise(
    PM10_sum = sum(PM10, na.rm = TRUE),
    PM2.5_sum = sum(PM2.5, na.rm = TRUE)
  ) %>%
  ungroup()

# 계절별 전체 PM10 및 PM2.5 합계 계산
total_seasonal_data <- SeoulWeather1 %>%
  group_by(Season) %>%
  summarise(
    total_PM10 = sum(PM10, na.rm = TRUE),
    total_PM2.5 = sum(PM2.5, na.rm = TRUE)
  )

# 계절별 총합을 기준으로 비율 계산
seasonal_wind_data <- seasonal_wind_data %>%
  left_join(total_seasonal_data, by = "Season") %>%
  mutate(
    PM10_ratio = PM10_sum / total_PM10,
    PM2.5_ratio = PM2.5_sum / total_PM2.5
  )

# 데이터 시각화 (계절별로 따로 그래프 생성)
seasons <- unique(seasonal_wind_data$Season)

for (season in seasons) {
  season_data <- seasonal_wind_data %>% filter(Season == season)
  
 p <- ggplot(season_data, aes(x = factor(풍향방위, levels = c("N", "NE", "E", "SE", "S", "SW", "W", "NW")))) +
    geom_line(aes(y = PM10_ratio, color = "PM10", group = 1), size = 1) +
    geom_line(aes(y = PM2.5_ratio, color = "PM2.5", group = 1), size = 1) +
    geom_point(aes(y = PM10_ratio, color = "PM10"), size = 2) +
    geom_point(aes(y = PM2.5_ratio, color = "PM2.5"), size = 2) +
    coord_polar(start = -pi/8) +
    scale_x_discrete(drop = FALSE, limits = c("N", "NE", "E", "SE", "S", "SW", "W", "NW")) +
    labs(y = "비율", color = "범례", title = paste(season, "PM10 및 PM2.5 비율")) +
    theme_minimal()
 
 print(p) 
}
```

```{r}
# 풍향 비율 찾기
SeoulWeather1 %>% group_by(풍향방위) %>% summarise(n=n()) %>% ungroup() %>% mutate(p=n/sum(n))

# 대상 데이터 프레임에서 풍향별 빈도 계산
df <- SeoulWeather1 %>% group_by(풍향방위) %>% summarise(n=n())
df
```

```{r}
#질소산화물과 풍향을 통한 미세먼지 분석
SeoulWeather3 <- SeoulWeather1 %>% filter(!is.na(NO2),!is.na(PM10), !is.na(PM2.5), !is.na(풍향.deg.), 풍향.deg.>0, 풍향.deg.<=360) %>%
  mutate(NO2 = 1000 * NO2) %>%   
  mutate(풍향.deg. = cut(풍향.deg., breaks = c(0, 22.5, 67.5, 112.5, 157.5, 202.5, 247.5, 292.5, 337.5, 360.0), 
                       right=TRUE, include.lowest=TRUE,
                       labels = c("N", "NE", "E", "SE", "S", "SW", "W", "NW", "N"))) %>% arrange(풍향.deg.)

mod1 <- lm(PM10~NO2, data=SeoulWeather3)
mod2 <- lm(PM2.5~NO2, data=SeoulWeather3)

# mod1의 잔차를 계산하고 데이터 프레임에 추가
SeoulWeather3$PM10_resid = residuals(mod1)

# mod2의 잔차를 계산하고 데이터 프레임에 추가
SeoulWeather3$PM2.5_resid = residuals(mod2)

#normalization
SeoulModel <- SeoulWeather3 %>% mutate(
  PM10 = (PM10 - mean(PM10)) / sd(PM10),
  PM2.5 = (PM2.5 - mean(PM2.5)) / sd(PM2.5)
)

PM10FromWhere <- SeoulModel %>% filter(PM10>2) %>% group_by(풍향.deg.) %>% summarise(n=n()) %>% ungroup() %>% summarise(풍향.deg., 비율 = n / sum(n))
PM2.5FromWhere <- SeoulModel %>% filter(PM2.5>2) %>% group_by(풍향.deg.) %>% summarise(n=n()) %>% ungroup() %>% summarise(풍향.deg., 비율 = n / sum(n))

PM10FromWhere
PM2.5FromWhere

mod3 <- coef(lm(PM10~NO2+풍향.deg., data=SeoulWeather3))
mod4 <- coef(lm(PM2.5~NO2+풍향.deg., data=SeoulWeather3))

tibble(names = names(mod3), mod3) %>% left_join(tibble(names = names(mod4), mod4), by="names")

```

```{r}
# mod1 모델 설명력
mod1_r_squared <- summary(mod1)$r.squared
```

```{r}
# mod2 모델 설명력
mod2_r_squared <- summary(mod2)$r.squared
```

```{r}
mod3_1 <- lm(PM10~NO2+풍향.deg., data=SeoulWeather3)

# mod3 모델 설명력
mod3_1_r_squared <- summary(mod3_1)$r.squared
```

```{r}
mod4_1 <- lm(PM2.5~NO2+풍향.deg., data=SeoulWeather3)

# mod3 모델 설명력
mod4_1_r_squared <- summary(mod4_1)$r.squared
```

```{r}
print(paste("mod1 R-squared: ", mod1_r_squared))
print(paste("mod2 R-squared: ", mod2_r_squared))
print(paste("mod3_1 R-squared: ", mod3_1_r_squared))
print(paste("mod4_1 R-squared: ", mod4_1_r_squared))

```

```{r}
# 풍향, 교통량 모두 고려  
weather_data <- SeoulWeather1
traffic_data <- filtered_data

# 교통량 데이터 준비
traffic_data_long <- traffic_data %>%
  gather(key = "시간", value = "교통량", -날짜, -영업소, -자료종류) %>%
  mutate(datetime = ymd(날짜) + hours(as.numeric(substr(시간, 1, nchar(시간)-1)))) %>%
  dplyr::select(datetime, 영업소, 교통량) %>%
  filter(교통량 < quantile(교통량, 0.99)) # 이상치 제거

# 각 영업소별 데이터 분리
traffic_seoul <- traffic_data_long %>% filter(영업소 == "서울")
traffic_seoseoul <- traffic_data_long %>% filter(영업소 == "서서울")
traffic_gunja <- traffic_data_long %>% filter(영업소 == "군자")

# 1시간 시간 차이를 반영
traffic_seoul$datetime <- traffic_seoul$datetime + hours(1)
traffic_seoseoul$datetime <- traffic_seoseoul$datetime + hours(1)
traffic_gunja$datetime <- traffic_gunja$datetime + hours(1)

# datetime 컬럼 생성 및 설정
weather_data <- weather_data %>%
  mutate(datetime = ymd_h(측정일시))

# 교통량 데이터와 미세먼지 데이터 결합
merged_data <- weather_data %>%
  left_join(traffic_seoul, by = "datetime") %>%
  rename(교통량_서울 = 교통량) %>%
  left_join(traffic_seoseoul, by = "datetime") %>%
  rename(교통량_서서울 = 교통량) %>%
  left_join(traffic_gunja, by = "datetime") %>%
  rename(교통량_군자 = 교통량)

# 8방위로 나누기 및 각 영업소에 맞는 변수 생성
merged_data <- merged_data %>%
  mutate(
    풍향_8방위 = case_when(
      (풍향.deg. > 0 & 풍향.deg. <= 22.5) | (풍향.deg. > 337.5 & 풍향.deg. <= 360) ~ "N",
      (풍향.deg. > 22.5 & 풍향.deg. <= 67.5) ~ "NE",
      (풍향.deg. > 67.5 & 풍향.deg. <= 112.5) ~ "E",
      (풍향.deg. > 112.5 & 풍향.deg. <= 157.5) ~ "SE",
      (풍향.deg. > 157.5 & 풍향.deg. <= 202.5) ~ "S",
      (풍향.deg. > 202.5 & 풍향.deg. <= 247.5) ~ "SW",
      (풍향.deg. > 247.5 & 풍향.deg. <= 292.5) ~ "W",
      (풍향.deg. > 292.5 & 풍향.deg. <= 337.5) ~ "NW",
      TRUE ~ NA_character_
    ),
    서서울_풍향 = case_when(
      풍향_8방위 == "W" ~ 1,
      풍향_8방위 == "SW" ~ 1,
      풍향_8방위 == "NW" ~ 1,
      TRUE ~ 0
    ),
    서울_풍향 = case_when(
      풍향_8방위 == "S" ~ 1,
      풍향_8방위 == "SE" ~ 1,
      풍향_8방위 == "NE" ~ 1,
      TRUE ~ 0
    ),
    군자_풍향 = case_when(
      풍향_8방위 == "E" ~ 1,
      풍향_8방위 == "SE" ~ 1,
      풍향_8방위 == "NW" ~ 1,
      TRUE ~ 0
    )
  )

```

```{r}
# 다중 회귀 분석: 미세먼지 (PM10)
pm10_model <- lm(PM10 ~ 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s., data = merged_data)

summary(pm10_model)
pm10_r_squared <- summary(pm10_model)$r.squared
```

```{r}
# 다중 회귀 분석: 미세먼지 NO2추가 (PM10)
pm10_model_2 <- lm(PM10 ~ CO + SO2 + NO2 + 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s. + 강수량.mm. + 현지기압.hPa. + 해면기압.hPa. + 습도..., data = merged_data)
summary(pm10_model_2)
pm10_2_r_squared <- summary(pm10_model_2)$r.squared
```


```{r}
# 다중 회귀 분석: 초미세먼지 (PM2.5)
pm25_model <- lm(PM2.5 ~ 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s., data = merged_data)
summary(pm25_model)
pm25_r_squared <- summary(pm25_model)$r.squared
```

```{r}
# 다중 회귀 분석: 초미세먼지 NO2 추가 (PM2.5)
pm25_model_2 <- lm(PM2.5 ~ CO + SO2 + NO2 + 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s. + 강수량.mm. + 현지기압.hPa. + 해면기압.hPa. + 습도..., data = merged_data)
summary(pm25_model_2)
pm25_2_r_squared <- summary(pm25_model_2)$r.squared
```

```{r}
# 다중 회귀 분석: 질소산화물
NO2_model <- lm(NO2 ~ 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s., data = merged_data)
summary(NO2_model)
NO2_r_squared <- summary(NO2_model)$r.squared

```

```{r}
print(paste("pm10_model_1 R-squared: ", pm10_r_squared))
print(paste("pm10_model_2 R-squared: ", pm10_2_r_squared))
print(paste("pm25_model_1 R-squared: ", pm25_r_squared))
print(paste("pm25_model_2 R-squared: ", pm25_2_r_squared))
print(paste("NO2_model R-squared: ", NO2_r_squared))

```

```{r}
# 결측치가 있는 행 제거
clean_data <- na.omit(merged_data)

# 로버스트 회귀 분석 
robust_pm10_model_2 <- rlm(PM10 ~ CO + SO2 + NO2 + 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s. + 강수량.mm. + 현지기압.hPa. + 해면기압.hPa. + 습도..., data = clean_data)

# 예측값 계산
predicted_values_10 <- predict(robust_pm10_model_2, clean_data)

# 실제 값과 예측값의 차이 계산
residuals_10 <- clean_data$PM10 - predicted_values_10
rss_10 <- sum(residuals_10^2)  
tss_10 <- sum((clean_data$PM10 - mean(clean_data$PM10)))^2

# R² 값 계산
r_squared_10 <- 1 - (rss_10/tss_10)
r_squared_10
```

```{r}
# 잔차 히스토그램
hist(residuals_10, breaks = 50, main = "Residuals Histogram", xlab = "Residuals")

# Q-Q 플롯
qqnorm(residuals_10)
qqline(residuals_10, col = "red")

```

```{r}
# 이상치 식별 (잔차가 특정 기준을 초과하는 경우)
threshold_10 <- 3 * sd(residuals_10)
outliers_10 <- abs(residuals_10) > threshold_10

# 이상치를 제거한 새로운 데이터 프레임 생성
clean_data_no_outliers <- clean_data[!outliers_10, ]

# 로버스트 회귀 분석 다시 실행
robust_pm10_model_2_no_outliers <- rlm(PM10 ~ CO + SO2 + NO2 + 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s. + 강수량.mm. + 현지기압.hPa. + 해면기압.hPa. + 습도..., data = clean_data_no_outliers)

# 예측값 계산
predicted_values_no_outliers_10 <- predict(robust_pm10_model_2_no_outliers, clean_data_no_outliers)

# 실제 값과 예측값의 차이 계산
residuals_no_outliers_10 <- clean_data_no_outliers$PM10 - predicted_values_no_outliers_10
rss_no_outliers_10 <- sum(residuals_no_outliers_10^2) 
tss_no_outliers_10 <- sum((clean_data_no_outliers$PM10 - mean(clean_data_no_outliers$PM10))^2) 
summary(robust_pm10_model_2_no_outliers)

# R² 값 계산
r_squared_no_outliers_10 <- 1 - (rss_no_outliers_10/tss_no_outliers_10)
r_squared_no_outliers_10
```

```{r}
# 로버스트 회귀 분석 
robust_pm2.5_model_2 <- rlm(PM2.5 ~ CO + SO2 + NO2 + 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s. + 강수량.mm. + 현지기압.hPa. + 해면기압.hPa. + 습도..., data = clean_data)

# 예측값 계산
predicted_values_2.5 <- predict(robust_pm2.5_model_2, clean_data)

# 실제 값과 예측값의 차이 계산
residuals_2.5 <- clean_data$PM2.5 - predicted_values_2.5
rss_2.5 <- sum(residuals_2.5^2)  
tss_2.5 <- sum((clean_data$PM2.5 - mean(clean_data$PM2.5)))^2

# R² 값 계산
r_squared_2.5 <- 1 - (rss_2.5/tss_2.5)
r_squared_2.5
```

```{r}
# 잔차 히스토그램
hist(residuals_2.5, breaks = 50, main = "Residuals Histogram", xlab = "Residuals")

# Q-Q 플롯
qqnorm(residuals_2.5)
qqline(residuals_2.5, col = "red")
```

```{r}
# 이상치 식별 (잔차가 특정 기준을 초과하는 경우)
threshold_2.5 <- 3 * sd(residuals_2.5)
outliers_2.5 <- abs(residuals_2.5) > threshold_2.5

# 이상치를 제거한 새로운 데이터 프레임 생성
clean_data_no_outliers <- clean_data[!outliers_2.5, ]

# 로버스트 회귀 분석 다시 실행
robust_pm2.5_model_2_no_outliers <- rlm(PM2.5 ~ CO + SO2 + NO2 + 교통량_서울 + 교통량_서서울 + 교통량_군자 + 서서울_풍향 + 서울_풍향 + 군자_풍향 + 풍속.m.s. + 강수량.mm. + 현지기압.hPa. + 해면기압.hPa. + 습도..., data = clean_data_no_outliers)

# 예측값 계산
predicted_values_no_outliers_2.5 <- predict(robust_pm2.5_model_2_no_outliers, clean_data_no_outliers)

# 실제 값과 예측값의 차이 계산
residuals_no_outliers_2.5 <- clean_data_no_outliers$PM2.5 - predicted_values_no_outliers_2.5
rss_no_outliers_2.5 <- sum(residuals_no_outliers_2.5^2)  
tss_no_outliers_2.5 <- sum((clean_data_no_outliers$PM2.5 - mean(clean_data_no_outliers$PM2.5))^2)  

summary(robust_pm2.5_model_2_no_outliers)

# R² 값 계산
r_squared_no_outliers_2.5 <- 1 - (rss_no_outliers_2.5/tss_no_outliers_2.5)
r_squared_no_outliers_2.5
```

```{r}
# 잔차 비교
ols_resid_2.5 <- resid(pm25_model_2)
rlm_resid_2.5 <- resid(robust_pm2.5_model_2_no_outliers)

# 히스토그램 비교
par(mfrow = c(1, 2))
hist(ols_resid_2.5, breaks = 50, main = "OLS Residuals", xlab = "Residuals", col = "blue", border = "white")
hist(rlm_resid_2.5, breaks = 50, main = "RLM Residuals", xlab = "Residuals", col = "red", border = "white")

```

```{r}
# 잔차 비교
ols_resid_10 <- resid(pm10_model_2)
rlm_resid_10 <- resid(robust_pm10_model_2_no_outliers)

# 히스토그램 비교
par(mfrow = c(1, 2))
hist(ols_resid_2.5, breaks = 50, main = "OLS Residuals", xlab = "Residuals", col = "blue", border = "white")
hist(rlm_resid_2.5, breaks = 50, main = "RLM Residuals", xlab = "Residuals", col = "red", border = "white")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
